### ISSUE TITLE
[BUG] New-ish materials (1.17+) not recognised by plugin

### ISSUE THREAD

**Issue by SleepyCatten** [PluginBugs/Issues-PocketMobs#10]
*Update - I think this was a PEBKAC error by me in terms of the ingredients. However, if you can check this and answer the query at the bottom, that'd be great*

**Describe the bug**
At least COPPER_INGOT and GLOW_INK_SAC are not recognised by the plugin. I have not tested other materials added from 1.17 and 1.18 to see if these are also missing. New entities could be missing too.

**To Reproduce**
1. Add the plugin to a supported server (Spigot, Paper etc.)
2. In the ball recipes file, try to use either COPPER_INGOT or GLOW_INK_SAC.
3. Start the server.
4. Warning messages will appear in the server console.

**Expected behavior**
All items and entities should be recognised by the plugin.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Server version: This server is running Paper version git-Paper-203 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5bb4549)
 - Client version: 1.18.1 (various different clients, some vanilla, some Forge, some Fabric, but the issue is on the server end)
 - Plugin version: 1.0.33

**Additional context**
I'm going by the material list here:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

I haven't tested to see whether any entity types are missing, per the list here:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html

Could you please also advise where lists like there are located?

- ALL_ANIMALS
- ALL_MONSTERS
- ALL_WATER_MOBS
- ALL_FISH
- ALL_MOBS
etc. 

I cannot find these anywhere other than the "discussions" section of the plugin.

**Comment by SleepyCatten** [comment]
Additional: GHAST_TEAR isn't recognised either. Perhaps some materials/mobs got missed?

**Comment by LoneDev6** [comment]
> Could you please also advise where lists like there are located?

This is basically the same thing in the internal game code.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Animals.html
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Monster.html
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Fish.html
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/WaterMob.html
