### ISSUE TITLE
[BUG] Plotsquared doesn't support it?

### ISSUE THREAD

**Issue by AnimeDrache** [PluginBugs/Issues-PocketMobs#14]
**Describe the bug**
We can't use it on plotsquared to catch animals there =(

**To Reproduce**
1. Try to catch an animal on a plot (or even th use a pokeball). Doesn't work to owners or trusted or visitors.

**Expected behavior**
Well it should work of course so we can transfer animals in der City.

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 100 (1.20.1)
 - Client version: normal 1.20.1
 - Plugin version: 1.0.33

**Additional context**

**Comment by AnimeDrache** [comment]
Hey I saw your answer on my review on the spigot website. I thank you and really hope we can fix it soon (I will then replace the review of course with a good one ♥)

**Comment by AnimeDrache** [comment]
So still no support on this plugin? Hm sad =/

**Comment by LoneDev6** [comment]
It should just work fine as PocketMobs checks for block placement and entity damage permission.
I will make some tests but last time I checked it worked fine with PlotSquared.
Please test again and let me know if the issue still occurs.
