### ISSUE TITLE
[Suggestion] Add option for make infinite usage ball

### ISSUE THREAD

**Issue by Dehkartes** [PluginBugs/Issues-PocketMobs#2]
**Is your feature request related to a problem? Please describe.**

I can't make infinite usage ball

**Describe the solution you'd like**

add option for make infinite usage ball

**Describe alternatives you've considered**

if max-usages: -1 in balls.yml, the ball has infinite usage

or 
     reduce-usages:
      use-ball: false
      
      Add this option allows unlimited ball usage

**Additional context**

**Comment by LoneDev6** [comment]
A new attribute `unlimited-usages: true` will be added to the balls.yml configuration.
Sorry for the delay
