### ISSUE TITLE
[BUG] The special ball causes the head item to disappear. 

### ISSUE THREAD

**Issue by XXY233** [PluginBugs/Issues-PocketMobs#3]
**Describe the bug**
When I used the ball, the item player_head disappeared out of thin air. 

**To Reproduce**
1. The client must install a mod which automatically refills the itemstack in the player's hand if there is any of the same item in the inventory. 
2. Throw a ball with mob inside. 
3. The item player_head disappeared.

**Expected behavior**
The item player_head will not disappear. 

**Video**

https://user-images.githubusercontent.com/46647646/126261858-54263507-fc0d-47a5-abba-f926c242e813.mp4
(The position of the backpack item in the upper left corner of the inventory. )

**Info (please complete the following information):**
 - Server version: 
![image](https://user-images.githubusercontent.com/46647646/126261368-4a9bb229-1550-447d-9fcc-723857d87af4.png)

 - Client version: 1.17.1
 - Plugin version: 1.0.30

**Additional context**
There are no error reports.

**Comment by LoneDev6** [comment]
Are you sure it's a PocketMobs issue?
I see the backpack moved into the hand slot for a millisecond when you throw the ball, it may be a Slimefun bug

**Comment by XXY233** [comment]
> I see the backpack moved into the hand slot for a millisecond when you throw the ball

Because his client installed a mod which automatically refills the itemstack in the player's hand if there is any of the same item in the inventory. 

I will do more tests to see if it is a bug in Slimefun.

**Comment by XXY233** [comment]
I can confirm now that it's not a Slimefun bug, and I have updated the steps of Reproduce.

https://user-images.githubusercontent.com/46647646/131495535-416a0a80-516a-4578-bfb4-5317fcf7f6c0.mp4

**Comment by LoneDev6** [comment]
Should be fixed in the next release.
Thanks
