### ISSUE TITLE
[BUG] ItemStack can't be null/Air!

### ISSUE THREAD

**Issue by DavidRSM29** [PluginBugs/Issues-PocketMobs#4]
**Describe the bug**
I don't know anything about the cause, because we just install it, but we haven't let users use it yet.

**To Reproduce**
None

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.5 and Java 16
 - Client version: Vanilla 1.16.5
 - Plugin version: 1.0.27

**Additional context**
https://pastebin.com/LFxWAzCS
[latest.log](https://github.com/PluginBugs/Issues-PocketMobs/files/6933792/latest.log)

**Comment by LoneDev6** [comment]
Hello,
sorry I don't really understand the issue

**Comment by DavidRSM29** [comment]
I mean there is no much information I can give you about the error, we just install the plugin, we didn't even use it yet, but it is throwing errors on the console like you can see in the log file and the pastebin link,

**Comment by DavidRSM29** [comment]
[latest (1).log](https://github.com/PluginBugs/Issues-PocketMobs/files/6949993/latest.1.log)
And here is an up-to-date log if you want to check it out, now despite the error, we get on the console, we have made the plugin accessible to the players, but the error is still there.

**Comment by LoneDev6** [comment]
I will publish an update that should remove this error
