### ISSUE TITLE
[BUG] Duplication bug

### ISSUE THREAD

**Issue by DavidRSM29** [PluginBugs/Issues-PocketMobs#5]
**Describe the bug**
When you throw a PocketMob ball directly to a hopper to free the entity, the ball gets duplicated.

**To Reproduce**
1. Get a PocketMob ball with an entity
2. throw the ball directly to the hopper
3. the ball gets duplicated

**Expected behavior**
That the item and the entity doesn't get duplicated

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.5
 - Client version: 1.16.5
 - Plugin version: 1.0.28

**Additional context**
https://youtu.be/TRdH2G3jdvY **- Video of the Bug**

**Comment by LoneDev6** [comment]
Thanks! This will be addressed
