### ISSUE TITLE
Variable failure

### ISSUE THREAD

**Issue by QingSongYaya** [PluginBugs/Issues-PocketMobs#7]
**Describe the bug**
The given item of Lang file: "§ 6 § L system § 8 § L » & A gives & E {item} & A to player & E {player}" is the player's name, and failed to catch: "& C failed to capture! Try again! & 7 ({value}% capture rate)" ({value} fails

paper 1.16.5
Plugin version:latest

No error reported

**Comment by LoneDev6** [comment]
I don't understand, sorry!
